### PR TITLE
Updating Dexmaker to support Mockito 2.1.0

### PR DESCRIPTION
**Pull request by tmtrademarked**
This PR updates Dexmaker to support the new interfaces of Mockito 2.1.0.

### CODE REVIEW

**Comment by tmtrademarked** [comment]
Ah - turns out this is pretty much the same as https://github.com/crittercism/dexmaker/pull/33, the only difference being the Mockito version. Apologies for the noise, I didn't see the original pull request. Let me know what you want me to do with this one.

**Comment by Amaumaury** [comment]
I'm still getting this error : 

`java.lang.AbstractMethodError: abstract method "org.mockito.plugins.MockMaker$TypeMockability org.mockito.plugins.MockMaker.isTypeMockable(java.lang.Class)"`

I don't know why. I might be doing something wrong.

**Comment by tmtrademarked** [comment]
Hmm - could you point me to a sample where you're seeing that? I never encountered that problem personally, so I may have missed an API.

**Comment by Amaumaury** [comment]
Basically what I tried was to make [this little example](https://github.com/bryanstern/dagger-instrumentation-example) work with mockito 2.1.0 in android studio.

The modifications I made were very simple : 

- In the repositories of the app/build.gradle add : 

`maven { url "https://jitpack.io" }`

- In the dependencies of the app/build.gradle remove : 

`compile 'com.google.dagger:dagger:2.0-SNAPSHOT'`
`apt 'com.google.dagger:dagger-compiler:2.0-SNAPSHOT'`
`debugCompile 'com.google.dexmaker:dexmaker:1.0'`
`debugCompile 'com.google.dexmaker:dexmaker-mockito:1.0'`
`debugCompile 'org.mockito:mockito-core:1.10.17'`

and add : 

`compile 'com.google.dagger:dagger:2.7'`
`apt 'com.google.dagger:dagger-compiler:2.7'`
`debugCompile 'com.github.blueapron:dexmaker:0.0.0'`
`debugCompile 'org.mockito:mockito-core:2.1.0'`

- In the app/src/debug/java/com.circle.testexample/Graph file change : 

`Dagger_Graph`

for

`DaggerGraph`

Then debug the MainActivityTest and you will see the exception I mentioned before.

**Comment by tmtrademarked** [comment]
Ah - try using com.github.blueapron:dexmaker:2.0 instead. The 0.0.0 release wasn't a working release. (I'm having trouble getting the example project running in my environment for other reasons, so I can't test it easily myself)

**Comment by Amaumaury** [comment]
Oh ok, you would probably want to update the README file then. So it worked with mockito 2.1.0 however when I try to enable final class mocks (more info [here](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#unmockable)) I get this exception : 

`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;`
`at net.bytebuddy.agent.ByteBuddyAgent$ProcessProvider$ForCurrentVm$ForLegacyVm.resolve(ByteBuddyAgent.java:728)`
`...`

Is that suppose to happen ?

**Comment by tmtrademarked** [comment]
I haven't attempted to support final class mocks yet - unfortunately, I
think that's going to be a much harder road. From what I can tell, it looks
like enabling that feature will require some additional work further down
in the stack. (I haven't spent a ton of time on this, but that's my initial
impression)

The README at https://github.com/blueapron/dexmaker uses the 2.0 library.
Is there another README somewhere I forgot to update? I can completely
believe I missed it somewhere. :-)

**Comment by Amaumaury** [comment]
My bad I was looking at ec3d50b 😅 

Anyway thanks for the help !

**Comment by drewhannay** [comment]
Thanks for the PR @tmtrademarked. Unfortunately after converting the project to gradle, your PR no longer applies cleanly, so I'm just going to add this change with #52.
